[project]
name = "test-one"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "prefect>=3.4.11",
    "prefect-github>=0.3.1",
]
